name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DockerHub Login
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          echo "${{secrets.DOCKER_HUB_USERNAME}}/nest-graphql:latest"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag blackmagex/nest-graphql:0.0.1
      - name: Deploy to DockerHub
        run: docker push blackmagex/nest-graphql:0.0.1